name: Build and Deploy Angular App

on:
  push:
    branches:
      - master

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    
    permissions:
      contents: write 
      id-token: write 
      pages: write

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '14'

    - name: Install dependencies
      run: npm ci

    - name: Build project
      run: npm run deploy

    - name: Setup Pages
      uses: actions/configure-pages@v2

    - name: Upload Artifact
      uses: actions/upload-pages-artifact@v2
      with:
        path: dist/scorekeeping-by-rounds
        
    - name: Deploy to GitHub Pages
      uses: actions/deploy-pages@v3
      id: deployment